//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantMenu_API.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class MealTag
    {
        public int Id_MealTag { get; set; }
        public int id_Meal { get; set; }
        public int id_Tag { get; set; }
    
        [JsonIgnore]
        public virtual Meal Meal { get; set; }
        [JsonIgnore]
        public virtual Tag Tag { get; set; }
    }
}
